# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commu.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63ommu.proto\";\n\x07Product\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"\x82\x01\n\x0c\x41OrderPlaced\x12\x0c\n\x04whid\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\x12\x11\n\tpackageid\x18\x04 \x02(\x03\x12\x18\n\x06things\x18\x05 \x03(\x0b\x32\x08.Product\x12\x11\n\tUPSuserid\x18\x06 \x01(\x03\x12\x0e\n\x06seqnum\x18\x07 \x02(\x03\"B\n\x0cUOrderPlaced\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"6\n\x13UArrivedAtWarehouse\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"F\n\x10\x41LoadingFinished\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"6\n\x11UPackageDelivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"e\n\x0c\x41\x43ommunicate\x12#\n\x0c\x61orderplaced\x18\x01 \x03(\x0b\x32\r.AOrderPlaced\x12\"\n\x07\x61loaded\x18\x02 \x03(\x0b\x32\x11.ALoadingFinished\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\"\x91\x01\n\x0cUCommunicate\x12#\n\x0cuorderplaced\x18\x01 \x03(\x0b\x32\r.UOrderPlaced\x12&\n\x08uarrived\x18\x02 \x03(\x0b\x32\x14.UArrivedAtWarehouse\x12&\n\nudelivered\x18\x03 \x03(\x0b\x32\x12.UPackageDelivered\x12\x0c\n\x04\x61\x63ks\x18\x04 \x03(\x03')
)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Product.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Product.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='Product.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=74,
)


_AORDERPLACED = _descriptor.Descriptor(
  name='AOrderPlaced',
  full_name='AOrderPlaced',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whid', full_name='AOrderPlaced.whid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='AOrderPlaced.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AOrderPlaced.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='AOrderPlaced.packageid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='things', full_name='AOrderPlaced.things', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UPSuserid', full_name='AOrderPlaced.UPSuserid', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AOrderPlaced.seqnum', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=207,
)


_UORDERPLACED = _descriptor.Descriptor(
  name='UOrderPlaced',
  full_name='UOrderPlaced',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UOrderPlaced.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UOrderPlaced.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UOrderPlaced.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=275,
)


_UARRIVEDATWAREHOUSE = _descriptor.Descriptor(
  name='UArrivedAtWarehouse',
  full_name='UArrivedAtWarehouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UArrivedAtWarehouse.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UArrivedAtWarehouse.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=331,
)


_ALOADINGFINISHED = _descriptor.Descriptor(
  name='ALoadingFinished',
  full_name='ALoadingFinished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='ALoadingFinished.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='ALoadingFinished.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='ALoadingFinished.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=403,
)


_UPACKAGEDELIVERED = _descriptor.Descriptor(
  name='UPackageDelivered',
  full_name='UPackageDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UPackageDelivered.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UPackageDelivered.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=459,
)


_ACOMMUNICATE = _descriptor.Descriptor(
  name='ACommunicate',
  full_name='ACommunicate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aorderplaced', full_name='ACommunicate.aorderplaced', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aloaded', full_name='ACommunicate.aloaded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='ACommunicate.acks', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=562,
)


_UCOMMUNICATE = _descriptor.Descriptor(
  name='UCommunicate',
  full_name='UCommunicate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uorderplaced', full_name='UCommunicate.uorderplaced', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uarrived', full_name='UCommunicate.uarrived', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='udelivered', full_name='UCommunicate.udelivered', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UCommunicate.acks', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=710,
)

_AORDERPLACED.fields_by_name['things'].message_type = _PRODUCT
_ACOMMUNICATE.fields_by_name['aorderplaced'].message_type = _AORDERPLACED
_ACOMMUNICATE.fields_by_name['aloaded'].message_type = _ALOADINGFINISHED
_UCOMMUNICATE.fields_by_name['uorderplaced'].message_type = _UORDERPLACED
_UCOMMUNICATE.fields_by_name['uarrived'].message_type = _UARRIVEDATWAREHOUSE
_UCOMMUNICATE.fields_by_name['udelivered'].message_type = _UPACKAGEDELIVERED
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['AOrderPlaced'] = _AORDERPLACED
DESCRIPTOR.message_types_by_name['UOrderPlaced'] = _UORDERPLACED
DESCRIPTOR.message_types_by_name['UArrivedAtWarehouse'] = _UARRIVEDATWAREHOUSE
DESCRIPTOR.message_types_by_name['ALoadingFinished'] = _ALOADINGFINISHED
DESCRIPTOR.message_types_by_name['UPackageDelivered'] = _UPACKAGEDELIVERED
DESCRIPTOR.message_types_by_name['ACommunicate'] = _ACOMMUNICATE
DESCRIPTOR.message_types_by_name['UCommunicate'] = _UCOMMUNICATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  ))
_sym_db.RegisterMessage(Product)

AOrderPlaced = _reflection.GeneratedProtocolMessageType('AOrderPlaced', (_message.Message,), dict(
  DESCRIPTOR = _AORDERPLACED,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:AOrderPlaced)
  ))
_sym_db.RegisterMessage(AOrderPlaced)

UOrderPlaced = _reflection.GeneratedProtocolMessageType('UOrderPlaced', (_message.Message,), dict(
  DESCRIPTOR = _UORDERPLACED,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:UOrderPlaced)
  ))
_sym_db.RegisterMessage(UOrderPlaced)

UArrivedAtWarehouse = _reflection.GeneratedProtocolMessageType('UArrivedAtWarehouse', (_message.Message,), dict(
  DESCRIPTOR = _UARRIVEDATWAREHOUSE,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:UArrivedAtWarehouse)
  ))
_sym_db.RegisterMessage(UArrivedAtWarehouse)

ALoadingFinished = _reflection.GeneratedProtocolMessageType('ALoadingFinished', (_message.Message,), dict(
  DESCRIPTOR = _ALOADINGFINISHED,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ALoadingFinished)
  ))
_sym_db.RegisterMessage(ALoadingFinished)

UPackageDelivered = _reflection.GeneratedProtocolMessageType('UPackageDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UPACKAGEDELIVERED,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:UPackageDelivered)
  ))
_sym_db.RegisterMessage(UPackageDelivered)

ACommunicate = _reflection.GeneratedProtocolMessageType('ACommunicate', (_message.Message,), dict(
  DESCRIPTOR = _ACOMMUNICATE,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:ACommunicate)
  ))
_sym_db.RegisterMessage(ACommunicate)

UCommunicate = _reflection.GeneratedProtocolMessageType('UCommunicate', (_message.Message,), dict(
  DESCRIPTOR = _UCOMMUNICATE,
  __module__ = 'commu_pb2'
  # @@protoc_insertion_point(class_scope:UCommunicate)
  ))
_sym_db.RegisterMessage(UCommunicate)


# @@protoc_insertion_point(module_scope)
